capitals = {'AFGHANISTAN': 'KABUL',
            'ALBANIA': 'TIRANA',
            'ALGERIA': 'ALGIERS',
            'ANDORRA': 'ANDORRA LA VELLA',
            'ANGOLA': 'LUANDA',
            'ANTIGUA & BARBUDA': "SAINT JOHN'S",
            'ARGENTINA': 'BUENOS AIRES', 
            'ARMENIA': 'YEREVAN', 
            'AUSTRALIA': 'CANBERRA', 
            'AUSTRIA': 'VIENNA', 
            'AZERBAIJAN': 'BAKU', 
            'BAHAMAS, THE': 'NASSAU', 
            'BAHRAIN': 'MANAMA', 
            'BANGLADESH': 'DHAKA', 
            'BARBADOS': 'BRIDGETOWN', 
            'BELARUS': 'MINSK', 
            'BELGIUM': 'BRUSSELS', 
            'BELIZE': 'BELMOPAN', 
            'BENIN': 'PORTO-NOVO', 
            'BHUTAN': 'THIMPHU', 
            'BOLIVIA': 'SUCRE', 
            'BOSNIA & HERZEGOVINA': 'SARAJEVO',
            'BOTSWANA': 'GABORONE', 
            'BRAZIL': 'BRASILIA', 
            'BRUNEI': 'BANDAR SERI BEGAWAN', 
            'BULGARIA': 'SOFIA', 
            'BURKINA FASO': 'OUAGADOUGOU', 
            'BURUNDI': 'GITEGA, BUJUMBURA', 
            'CABO VERDE': 'PRAIA', 
            'CAMBODIA': 'PHNOM PENH', 
            'CAMEROON': 'YAOUNDE', 
            'CANADA': 'OTTAWA', 
            'CENTRAL AFRICAN REPUBLIC': 'BANGUI', 
            'CHAD': "N'DJAMENA", 
            'CHILE': 'SANTIAGO', 
            'CHINA': 'BEIJING', 
            'COLOMBIA': 'BOGOT',
            'COMOROS': 'MORONI', 
            'CONGO, DEMOCRATIC REPUBLIC OF THE': 'KINSHASA', 
            'CONGO, REPUBLIC OF THE': 'BRAZZAVILLE',
            'COSTA RICA': 'SAN JOSE',  
            'CROATIA':'ZAGREB',
            'CUBA':'HAVANA',
            'CYPRUS':'NICOSIA',
            'Czech Republic': 'PRAGUE',
            'DENMARK': 'COPENHAGEN',
            'DJIBOUTI': 'DJIBOUTI CITY',
            'DOMINICA':'ROSEAU',
            'DOMINICAN REPUBLIC':'SANTO DOMINGO', 
            'ECUADOR':'QUITO',
            'EGYPT':'CAIRO',
            'EL SALVADOR':'SAN SALVADOR',
            'EQUATORIAL GUINEA':'MALABO',
            'ERITREA':'ASMARA', 
            'ESTONIA':'TALLINN',
            'ESWATINI (formerly Swaziland)': 'MBABANE',
            'ETHIOPIA': 'ADDIS ABABA',
            'FIJI': 'SUVA', 
            'FINLAND': 'HELSINKI', 
            'FRANCE': 'PARIS', 
            'GABON': 'LIBREVILLE', 
            'GAMBIA, THE': 'BANJUL', 
            'GEORGIA': 'TBILISI', 
            'GERMANY': 'BERLIN', 
            'GHANA': 'ACCRA', 
            'GREECE': 'ATHENS', 
            'GRENADA': "SAINT GEORGE'S", 
            'GUATEMALA': 'GUATEMALA CITY', 
            'GUINEA': 'CONAKRY', 
            'GUINEA-BISSAU': 'BISSAU', 
            'GUYANA': 'GEORGETOWN', 
            'HAITI': 'PORT-AU-PRINCE', 
            'HONDURAS': 'TEGUCIGALPA', 
            'HUNGARY': 'BUDAPEST', 
            'ICELAND': 'REYKJAVIK', 
            'INDIA': 'NEW DELHI', 
            'INDONESIA': 'JAKARTA', 
            'IRAN': 'TEHRAN', 
            'IRAQ': 'BAGHDAD', 
            'IRELAND': 'DUBLIN', 
            'ISRAEL': 'JERUSALEM', 
            'ITALY': 'ROME', 
            'JAMAICA': 'KINGSTON', 
            'JAPAN': 'TOKYO', 
            'JORDAN': 'AMMAN', 
            'KAZAKHSTAN': 'NUR-SULTAN', 
            'KENYA': 'NAIROBI', 
            'KIRIBATI': 'SOUTH TARAWA', 
            'KOSOVO': 'PRISTINA', 
            'KUWAIT': 'KUWAIT CITY', 
            'KYRGYZSTAN': 'BISHKEK', 
            'LAOS': 'VIENTIANE', 
            'LATVIA': 'RIGA', 
            'LEBANON': 'BEIRUT', 
            'LESOTHO': 'MASERU', 
            'LIBERIA': 'MONROVIA', 
            'LIBYA': 'TRIPOLI', 
            'LIECHTENSTEIN': 'VADUZ', 
            'LITHUANIA': 'VILNIUS', 
            'TURKMENISTAN':'ASHGABAT',
            'TUVALU':'FUNAFUTI',
            'UGANDA':'KAMPALA', 
            'UKRAINE':'KIEV',
            'UNITED ARAB EMIRATES' : 'ABU DHABI',
            'UNITED KINGDOM ': 'LONDON', 
            'UNITED STATES OF AMERICA': 'WASHINGTON, DC',
            'URUGUAY':'MONTEVIDEO', 
            'UZBEKISTAN':'TASHKENT',
            'VANUATU':'PORT VILA',
            'VENEZUELA': 'CARACAS', 
            'VIETNAM': 'HANOI', 
            'YEMEN': "SANA'A", 
            'ZAMBIA': 'LUSAKA', 
            'ZIMBABWE': 'HARARE'}